;ORG ADDRESS AND BOOT TRACK FOR MODEL I
;USING TRSDOS 2.3 DATA DISK AS THE BASE (DIR TRACK 17)
	ORG	4200H
;THE FIRST THREE SECTORS OF A BOOT DISK
;INDICATE THE LOCATION OF THE DIRECTORY.
;FOR MY DISKS...LDOS 5 (MODEL III/4): TRACK 20
;               TRSDOS 2.1 (MODEL I): TRACK 17
START	NOP
	CP	11H
