;ORG ADDRESS AND BOOT TRACK FOR MODEL III/4/4P
;USING LDOS 5.3.1 DATA DISK AS THE BASE (DIR TRACK 20)
	ORG	4300H
;THE FIRST THREE SECTORS OF A BOOT DISK
;INDICATE THE LOCATION OF THE DIRECTORY.
;FOR MY DISKS...LDOS 5 (MODEL III/4): TRACK 20
;               TRSDOS 2.1 (MODEL I): TRACK 17
START	NOP
	CP	14H
